// ===============================
// ASSETS
// ===============================

import {
  finance_data, quant_analysis, machine, finance_engineer, 
  css, git, html, aws, python, vba, snowflake, sql, anaconda, 
  tala, laurus, jlg, telus, rws, gnp, amib,
  amib_cert, uc_davis, google,
} from "../assets";

// ===============================
// NAVIGATION
// ===============================

export const navLinks = Object.freeze([
  { id: "about", title: "About" },
  { id: "work", title: "Work" },
  { id: "contact", title: "Contact" },
]);

// ===============================
// SERVICES
// ===============================

export const services = Object.freeze([
  {
    title: "Financial Data Science",
    icon: finance_data,
  },
  {
    title: "Quantitative Analysis",
    icon: quant_analysis,
  },
  {
    title: "Machine Learning",
    icon: machine,
  },
  {
    title: "Fintech",
    icon: finance_engineer,
  },
]);

// ===============================
// TECHNOLOGIES
// ===============================

export const technologies = Object.freeze([
  { name: "Python", icon: python },
  { name: "AWS", icon: aws },
  { name: "Snowflake", icon: snowflake },
  { name: "SQL", icon: sql },
  { name: "VBA", icon: vba },
  { name: "Git", icon: git },
  { name: "HTML", icon: html },
  { name: "CSS", icon: css },
  { name: "Anaconda", icon: anaconda },
]);

// ===============================
// EXPERIENCE
// ===============================

export const experiences = Object.freeze([
  {
    title: "Reconciliation Analyst",
    company_name: "Tala Mobile",
    icon: tala,
    iconBg: "#ffffff",
    date: "May 2026 - Present",
    points: [
      "Supporting FinTech reconciliations across 6 countries, covering 1.5M+ monthly transactions.",
      "Automated reconciliations with Python, Snowflake, SQL, Pandas, and VBA, enabling ~2-hour processing and T+1 discrepancy visibility.",
    ],
  },
  {
    title: "Financial Analyst",
    company_name: "JLG Industries",
    icon: jlg,
    iconBg: "#ffffff",
    date: "May 2025 - Dec 2025",
    points: [
      "Regularized and reconciled MXN $1.12B through financial analysis and process automation.",
      "Strengthened financial controls and improved reliability of accounting and reporting processes.",
    ],
  },
  {
    title: "Financial Data Scientist",
    company_name: "Laurus Consulting",
    icon: laurus,
    iconBg: "#ffffff",
    date: "Jul 2024 - Feb 2025",
    points: [
      "Developed machine learning models for financial analysis, investment insights, and automation.",
      "Applied AI techniques to support decision-making and risk management processes.",
    ],
  },
  {
    title: "Online Data Analyst",
    company_name: "TELUS Digital",
    icon: telus,
    iconBg: "#ffffff",
    date: "Nov 2023 - Oct 2024",
    points: [
      "Analyzed and validated large datasets used to train and evaluate AI systems.",
      "Ensured data quality, consistency, and relevance for machine learning models.",
    ],
  },
  {
    title: "Search Evaluator for AI Models",
    company_name: "RWS Group",
    icon: rws,
    iconBg: "#ffffff",
    date: "Jan 2024 - Aug 2024",
    points: [
      "Evaluated search engine outputs generated by AI models for semantic accuracy.",
      "Improved model alignment by assessing relevance, data quality, and ranking criteria.",
    ],
  },
  {
    title: "Insurance Agent",
    company_name: "GNP Seguros",
    icon: gnp,
    iconBg: "#ffffff",
    date: "Jun 2023 - Dec 2023",
    points: [
      "Analyzed client financial needs to design personalized insurance solutions.",
      "Developed sales and risk evaluation skills within the insurance and financial services sector.",
    ],
  },
]);

// ===============================
// CERTIFICATIONS
// ===============================

export const testimonials = Object.freeze([
  {
    certification: "Investment Strategies Advisor (Series 210)",
    company: "AMIB",
    month: "June",
    year: "2026",
    image: amib_cert,
  },
  {
    certification: "SQL Basics for Data Science Specialization",
    company: "University of California",
    month: "April",
    year: "2024",
    image: uc_davis,
  },
  {
    certification: "Google Data Analytics Professional Certificate",
    company: "Google",
    month: "April",
    year: "2023",
    image: google,
  },
]);

// ===============================
// PROJECTS
// ===============================

export const projects = Object.freeze([
  {
  name: "AMIB-3 Certification Guide",
  description:
    "Comprehensive study guide for the AMIB-3 Investment Strategies Advisor certification exam.",
  tags: [
    { name: "amib-3", color: "blue-text-gradient" },
    { name: "financial-education", color: "green-text-gradient" },
    { name: "investments", color: "pink-text-gradient" },
  ],
  image: amib,
  source_code_link: "/guia-amib-3/",
  },
]);