// ===============================
// ASSETS
// ===============================

import {
  finance_data, quant_analysis, machine, finance_engineer, 
  css, git, html, aws, python, r, spark, sql, anaconda, 
  laurus, jlg, telus, rws, gnp, amib, mask, nomad, 
  uc_davis, microsoft, domestika, google, aws_logo,
} from "../assets";

// ===============================
// NAVIGATION
// ===============================

export const navLinks = Object.freeze([
  { id: "about", title: "About" },
  { id: "work", title: "Work" },
  { id: "contact", title: "Contact" },
]);

// ===============================
// SERVICES
// ===============================

export const services = Object.freeze([
  {
    title: "Financial Data Science",
    icon: finance_data,
  },
  {
    title: "Quantitative Analysis",
    icon: quant_analysis,
  },
  {
    title: "Machine Learning",
    icon: machine,
  },
  {
    title: "Financial Engineering",
    icon: finance_engineer,
  },
]);

// ===============================
// TECHNOLOGIES
// ===============================

export const technologies = Object.freeze([
  { name: "Python", icon: python },
  { name: "AWS", icon: aws },
  { name: "Apache Spark", icon: spark },
  { name: "SQL", icon: sql },
  { name: "R", icon: r },
  { name: "Git", icon: git },
  { name: "HTML", icon: html },
  { name: "CSS", icon: css },
  { name: "Anaconda", icon: anaconda },
]);

// ===============================
// EXPERIENCE
// ===============================

export const experiences = Object.freeze([
  {
    title: "Financial Analyst",
    company_name: "JLG Industries",
    icon: jlg,
    iconBg: "#ffffff",
    date: "May 2025 - Dec 2025",
    points: [
      "Regularized and reconciled MXN $1.12B through financial analysis and process automation.",
      "Strengthened financial controls and improved reliability of accounting and reporting processes.",
    ],
  },
  {
    title: "Financial Data Scientist",
    company_name: "Laurus Consulting",
    icon: laurus,
    iconBg: "#ffffff",
    date: "Jul 2024 - Feb 2025",
    points: [
      "Developed machine learning models for financial analysis, investment insights, and automation.",
      "Applied AI techniques to support decision-making and risk management processes.",
    ],
  },
  {
    title: "Online Data Analyst",
    company_name: "TELUS Digital",
    icon: telus,
    iconBg: "#ffffff",
    date: "Nov 2023 - Oct 2024",
    points: [
      "Analyzed and validated large datasets used to train and evaluate AI systems.",
      "Ensured data quality, consistency, and relevance for machine learning models.",
    ],
  },
  {
    title: "Search Evaluator for AI Models",
    company_name: "RWS Group",
    icon: rws,
    iconBg: "#ffffff",
    date: "Jan 2024 - Aug 2024",
    points: [
      "Evaluated search engine outputs generated by AI models for semantic accuracy.",
      "Improved model alignment by assessing relevance, data quality, and ranking criteria.",
    ],
  },
  {
    title: "Insurance Agent",
    company_name: "GNP Seguros",
    icon: gnp,
    iconBg: "#ffffff",
    date: "Jun 2023 - Dec 2023",
    points: [
      "Analyzed client financial needs to design personalized insurance solutions.",
      "Developed sales and risk evaluation skills within the insurance and financial services sector.",
    ],
  },
]);

// ===============================
// CERTIFICATIONS
// ===============================

export const testimonials = Object.freeze([
  {
    certification: "SQL Basics for Data Science",
    company: "University of California",
    month: "April",
    year: "2024",
    image: uc_davis,
  },
  {
    certification: "Data Analysis Fundamentals with Excel",
    company: "Microsoft",
    month: "February",
    year: "2024",
    image: microsoft,
  },
  {
    certification: "Introduction to AI with Python",
    company: "Domestika",
    month: "January",
    year: "2024",
    image: domestika,
  },
  {
    certification: "Google Data Analytics",
    company: "Google",
    month: "April",
    year: "2023",
    image: google,
  },
  {
    certification: "Cloud Practitioner",
    company: "Amazon Web Services",
    month: "January",
    year: "2023",
    image: aws_logo,
  },
]);

// ===============================
// PROJECTS
// ===============================

export const projects = Object.freeze([
  {
  name: "AMIB-3 Certification Guide",
  description:
    "Comprehensive study guide for the AMIB-3 Investment Strategies Advisor certification exam.",
  tags: [
    { name: "amib-3", color: "blue-text-gradient" },
    { name: "financial-education", color: "green-text-gradient" },
    { name: "investments", color: "pink-text-gradient" },
  ],
  image: amib,
  source_code_link: "/guia-amib-3/index.html",
  },
  {
    name: "Mask Detection Neural Network",
    description:
      "CNN mask detection model built with TensorFlow using MobileNetV2 transfer learning.",
    tags: [
      { name: "machine-learning", color: "blue-text-gradient" },
      { name: "python", color: "green-text-gradient" },
      { name: "neural networks", color: "pink-text-gradient" },
    ],
    image: mask,
    source_code_link:
      "https://www.kaggle.com/code/jorgesamuelyanas/mask-detection-neural-network-for-safety",
  },
  {
    name: "Nomad Cost of Living Analysis",
    description:
      "Global cost-of-living analysis and visualization using Nomad List data in Tableau for country comparisons.",
    tags: [
      { name: "data-visualization", color: "blue-text-gradient" },
      { name: "data-analysis", color: "green-text-gradient" },
      { name: "data-cleaning", color: "pink-text-gradient" },
    ],
    image: nomad,
    source_code_link:
      "https://www.kaggle.com/code/jorgesamuelyanas/the-nomad-disease/notebook",
  },
]);